#include <CLHEP/Units/SystemOfUnits.h>
#include "G4SystemOfUnits.hh"
#include "CLHEP/Units/PhysicalConstants.h"
//#include </home/annemarie/programs/geant4.10.0p02/install/include/Geant4/CLHEP/Units/SystemOfUnits.h>

using CLHEP::amu_c2;
using CLHEP::Avogadro;
using CLHEP::Bohr_radius;
using CLHEP::c_light;
using CLHEP::c_squared;
using CLHEP::electron_mass_c2;
using CLHEP::e_squared;
using CLHEP::h_Planck;
using CLHEP::hbar_Planck;
using CLHEP::mu0;
using CLHEP::pi;
using CLHEP::twopi;
using CLHEP::k_Boltzmann;
using CLHEP::STP_Temperature;
