/vis/open VRML2FILE
/vis/scene/create
/vis/viewer/set/viewpointVector 0 -1 0
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/projection p 20
/vis/viewer/set/lineSegmentsPerCircle 128
/vis/viewer/set/lightsVector 0.0 0.0 1.0
/vis/viewer/set/lightsMove obj

/vis/sceneHandler/attach
#/vis/viewer/set/viewpointThetaPhi 0.0 90 deg
##/vis/viewer/flush
/vis/scene/add/volume
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate
##/vis/disable
